# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170603_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='image',
            field=models.ImageField(default=123, height_field='height', upload_to='', width_field='width'),
            preserve_default=False,
        ),
    ]
