# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20170603_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('茶類', '茶類'), ('果茶類', '果茶類'), ('口感類', '口感類')], max_length=200),
        ),
    ]
