# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 13:32
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20170603_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('茶類', '茶類'), ('果茶類', '果茶類'), ('口感類', '口感類')], max_length=10),
        ),
        migrations.AlterField(
            model_name='drink',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('茶類', '茶類'), ('果茶類', '果茶類'), ('口感類', '口感類')], max_length=10),
        ),
    ]
