# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 15:32
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20170603_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='cate',
        ),
        migrations.AddField(
            model_name='drink',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('招牌', '招牌'), ('茶類', '茶類'), ('奶茶類', '奶茶類'), ('果茶類', '果茶類'), ('特調茶類', '特調茶類'), ('抹茶類', '抹茶類'), ('嚼勁口感類', '嚼勁口感類'), ('果汁類', '果汁類'), ('奶,果昔類', '奶,果昔類'), ('鮮奶類', '鮮奶類'), ('拿鐵類', '拿鐵類')], default=5, max_length=46),
            preserve_default=False,
        ),
    ]
