# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 16:44
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20170603_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('招牌', '招牌'), ('茶類', '茶類'), ('奶茶類', '奶茶類'), ('果茶類', '果茶類'), ('特調茶類', '特調茶類'), ('抹茶類', '抹茶類'), ('嚼勁口感類', '嚼勁口感類'), ('果汁類', '果汁類'), ('水果類', '果汁類'), ('奶,果昔類', '奶,果昔類'), ('鮮奶類', '鮮奶類'), ('拿鐵類', '拿鐵類')], max_length=50),
        ),
    ]
