# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20170607_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Store'),
        ),
    ]
